package retcode

// BizType ...
type BizType int

// ErrorType ...
type ErrorType int

// BizType ...
const (
	// BizTypeBrowserExt ...
	BizTypeBrowserExt BizType = 101
)

// ErrorTypes ...
const (
	// ErrorTypeParamsInvalid ...
	ErrorTypeParamsInvalid ErrorType = 1
	// ErrorTypeBusinessErr ...
	ErrorTypeBusinessErr ErrorType = 2
	// ErrorTypeReqLimit ...
	ErrorTypeReqLimit ErrorType = 3
	// ErrorTypeRPCFail ...
	ErrorTypeRPCFail ErrorType = 4
	// ErrorTypeDBFail ...
	ErrorTypeDBFail ErrorType = 5
)
